rootProject.name = 'kafka'

include 'infra-message-queue'
include 'kafka-study'
include 'kafka-connect'
include 'kafka-redis-compare'
include 'kafka-retry-dlt'
include 'kafka-notification:notification-domain'
include 'kafka-notification:notification-contract'
include 'kafka-notification:notification-provider-sandbox'
include 'kafka-notification:notification-producer-app'
include 'kafka-notification:notification-worker-app'
